version: "3.4"
services:
  www:
    image: node:15.14.0
    working_dir: /app
    command: >
      sh -c "npm install -g @quasar/cli@1.2.2 && npm install && npm run start"
    volumes:
      - ${PWD}/apps:/app:delegated
