version: "3.4"
networks:
  proxynetwork:
    external: true
services:
  www:
    image: koromerzhin/nodejs:1.1.3-quasar
    volumes:
      - ${PWD}/apps:/app
    networks:
      - proxynetwork
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.quasar.rule=Host(`quasar.traefik.me`)"
        - "traefik.http.routers.quasar-tls.tls.domains[0].main=quasar.traefik.me"
        - "traefik.http.routers.quasar-tls.tls.domains[0].sans=quasar-*.traefik.me"
        - "traefik.http.services.quasar.loadbalancer.server.port=80"
