version: "3.4"
services:
  www:
    image: node:19.9.0
    working_dir: /app
    command: >
      sh -c "npm install -g @quasar/cli && npm install && quasar dev"
    volumes:
      - ${PWD}/apps:/app:delegated
