version: "3.4"
networks:
  proxylampy:
    external: true
  net:
    driver: overlay
    attachable: true
services:
  exec:
    image: koromerzhin/quasar:1.1.3
    volumes:
      - ${PWD}/apps:/app
    command: sh -c "npm install"
    deploy:
      restart_policy:
        condition: none
      labels:
        - "traefik.enable=false"
  www:
    image: koromerzhin/nodejs:1.1.3-quasar
    volumes:
      - ${PWD}/apps:/app
    networks:
      - proxylampy
      - net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.quasar.rule=HostRegexp(`quasar.traefik.me`, `quasar.{ip:.*}.traefik.me`)"
        - "traefik.http.services.quasar.loadbalancer.server.port=80"
