version: "3.4"
networks:
  proxylampy:
    external: true
services:
  www:
    image: node:22.20.0
    working_dir: /app
    command: >
      sh -c "npm install -g @quasar/cli && npm install && quasar dev"
    volumes:
      - ${PWD}/apps:/app:delegated
    networks:
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.quasar.rule=Host(`quasar.traefik.me`)"
        - "traefik.http.routers.quasar-tls.tls.domains[0].main=quasar.traefik.me"
        - "traefik.http.routers.quasar.tls=true"
        - "traefik.http.services.quasar.loadbalancer.server.port=9000"
